deepinsight/insightface

- deploy/mtcnn_detector.py
Current code will have an error for Python 3 because of zip package. I enabled the code compatible with Python 3 with only a little change.
> Compatible with Python 3.

- RetinaFace/rcnn/symbol/symbol_mnet.py
- RetinaFace/rcnn/symbol/symbol_resnet.py
Thanks for your attention. **Insightface** is the most fancy face project I have ever seen. Hope the small correction could make it better. 
Solving the error: ``No module named 'symbol_common'``
>  Fix the prefix of symbol_common import 

- recognition/sample_config.py
- recognition/symbol/vargfacenet.py
- recognition/train.py
- recognition/train_parall.py
add vargfacenet.py
modify train.py/train_parall.py/sample_config.py
> add vargfacenet

- recognition/partial_fc/mxnet/evaluation/example.sh
- recognition/partial_fc/mxnet/evaluation/ijb.py
bug fixes: now it works correctly with models with embedding layers
> Fixed the problem that pfc/mxnet/evaluate/ijb.py will raise error with the model with embedding layer

- evaluation/IJB/IJB_evals.py
Fix [IJBC evaluating issue](https://github.com/deepinsight/insightface/pull/1349#issuecomment-748953774) by using `pd.read_csv` instead of `np.loadtxt`. Tested scenarios: `IJBB` / `IJBC` in `11` / `1N`.
- `IJBC` `11` result
|                                                 |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
|:------------------------------------------------|---------:|---------:|---------:|---------:|---------:|---------:|
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D1F1 | 0.882855 | 0.940021 | 0.96073  | 0.974638 | 0.983331 | 0.991001 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D1F0 | 0.87948  | 0.938692 | 0.959145 | 0.973104 | 0.982359 | 0.990387 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D0F1 | 0.86409  | 0.933016 | 0.958122 | 0.973207 | …
> Fix IJBC evaluating issue in IJB_evals.py by replacing np.loadtxt with pd.read_csv

- evaluation/IJB/IJB_evals.py
- Fix 1N evaluation in `IJB_evals.py`
- [Issue evaluating IJB 1N](https://github.com/deepinsight/insightface/pull/1364#issuecomment-753438504)
- [Issue evaluating IJB 1N](https://github.com/deepinsight/insightface/pull/1349#issuecomment-753342776)
- Add a pytorch model interface that could be used to evaluating pytorch model saved by `torch.jit.save`
- Example saving the entire pytorch model by `torch.jit.save`:
```py
import torch
from backbones import iresnet50, iresnet100
resnet = iresnet50().cuda()
weight = torch.load('partial_fc_glint360k_r50/16backbone.pth')
resnet.load_state_dict(weight)
resnet.eval()
xx = torch.randn(1, 3, 112, 112).cuda()
traced_cell = torch.jit.trace(resnet, (xx))
torch.jit.save(traced_cell, 'iresnet50.pth')
```
- Result on `IJBB 1:1` `iresnet50`
```py …
```
> Fix 1N evaluation in IJB_evals.py and add pytorch model interface

- README.md
typo in academic and recognition has been fixed
> README typos fixed

- recognition/arcface_torch/backbones/__init__.py
- recognition/arcface_torch/backbones/mobilefacenet.py
- recognition/arcface_torch/train.py
1. Add new backbone mobilefacenet from cavaface
```text
Train on ms1m and evaluate on lfw 
[lfw]Accuracy-Flip: 0.99567+-0.00238
```
2. Fixed error while change embedding size in `config.py`
> Add mobilefacenet for arcface_torch

- recognition/_tools_/cpp_align/face_align.h
Hi, we created the issue https://github.com/deepinsight/insightface/issues/1559
We found that in some fringe cases, the function  cv::Mat similarTransform in face_align.h would return wrong results , which would lead to upside down aligned face. 
Some examples images are given [here](https://drive.google.com/file/d/1Y7I0ulZLr7ycWDNdY8wkux3LgLbN-LwJ/view)
After debugging without success, we compared the results of the code with the python version. While for most of the images, your code worked perfectly, for some odd cases, it would fail. We transplanted the code from Python back to C++ and found that there were some difference in the way you compute matrix T compared to the Python version, which lead to failed cases.
We were able to fix the code by changing some of the calculations. Face …
> Fix align face bug for odd cases

- model_zoo/README.md
> add paddle model zoo

- recognition/_evaluation_/ijb/ijb_evals.py
I'm told a new PR is welcome by @nttstar , so I create this again. :)
- Related issue [calculating 1:N DIR-FAR in IJB evaluation](https://github.com/deepinsight/insightface/pull/1364#issuecomment-757717175).
- Last PR is [Fix IJB 1:N evaluation in IJB_evals.py #1387](https://github.com/deepinsight/insightface/pull/1387). Detail explanation of `1:N` calculation is also there.
- Add `ONNX` model support.
- **Run tests**. Full log is attenched [ijb_evals.log](https://github.com/deepinsight/insightface/files/7109081/ijb_evals.log).
```sh
$ CUDA_VISIBLE_DEVICES='1' ./ijb_evals.py -m glint360k_r18.onnx -d /datasets/IJB_release/ -s IJBB
$ CUDA_VISIBLE_DEVICES='1' ./ijb_evals.py -m glint360k_r18.onnx -d /datasets/IJB_release/ -s IJBC
```
|                       |   1e-06 |    1e-05 |   0.0001 | …
> Fix IJB 1:N evaluation in ijb_evals.py

- recognition/arcface_oneflow/function.py
- recognition/arcface_oneflow/graph.py
- recognition/arcface_oneflow/utils/utils_callbacks.py
- recognition/arcface_oneflow/val.py
> fix path errors

- README.md
- recognition/README.md
> Arcface oneflow

- README.md
- detection/scrfd/README.md
MNN/TNN/NCNN/ONNXRuntime C++ demos for ArcFace and SCRFD.
- ONNXRuntime C++: [ArcFace-ONNXRuntime](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/cv/glint_arcface.cpp)
- MNN: [ArcFace-MNN](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/mnn/cv/mnn_glint_arcface.cpp)
- TNN: [ArcFace-TNN](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/tnn/cv/tnn_glint_arcface.cpp)
- NCNN: [ArcFace-NCNN](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ncnn/cv/ncnn_glint_arcface.cpp)  
usage demo: 
* [lite.ai.toolkit-face-recognition](https://github.com/DefTruth/lite.ai.toolkit#lite.ai.toolkit-face-recognition)  
* [test_lite_glint_arcface.cpp](https://github.com/DefTruth/lite.ai.toolkit/blob/main/examples/lite/cv/test_lite_glint_arcface.cpp)
test output:  
- …
> add SCRFD/ArcFace MNN/TNN/NCNN/ONNXRuntime C++ demo

- README.md
- detection/scrfd/README.md
Add link to [project](https://github.com/SthPhoenix/InsightFace-REST) using Python TensorRT execution backend for inference of ArcFace, Retinaface and SCRFD models. 
This project also provides:
-  FastAPI  based  REST API 
-  Dockerfiles to quickly deploy face recognition services
-  Faster SCRFD implementation using numba NJIT
-  Retrained SCRFD models to fix bug with large faces ( #1518)
-  Batch inference with SCRFD and ArcFace models
> Add TensorRT python demo

- recognition/arcface_paddle/tools/convert_image_bin.py
arcface_paddle convert image to bin: import error!
> fix import error

- parsing/dml_csr/dataset/datasets.py
- parsing/dml_csr/loss/consistency_loss.py
- parsing/dml_csr/loss/criterion.py
- parsing/dml_csr/loss/kl_loss.py
- parsing/dml_csr/loss/lovasz_softmax.py
- parsing/dml_csr/networks/dml_csr.py
- parsing/dml_csr/networks/modules/ddgcn.py
- parsing/dml_csr/networks/modules/edges.py
- parsing/dml_csr/networks/modules/parsing.py
- parsing/dml_csr/networks/modules/util.py
- parsing/dml_csr/test.py
- parsing/dml_csr/train.py
- parsing/dml_csr/utils/encoding.py
- parsing/dml_csr/utils/logging.py
- parsing/dml_csr/utils/miou.py
- parsing/dml_csr/utils/schp.py
- parsing/dml_csr/utils/transforms.py
- parsing/dml_csr/utils/utils.py
- parsing/dml_csr/utils/warmup_scheduler.py
@jiankangdeng @nttstar Pls take a look.
> face_parsing_code

- recognition/arcface_torch/configs/ms1mv3_mbf_resume.py
- recognition/arcface_torch/lr_scheduler.py
- recognition/arcface_torch/partial_fc.py
- recognition/arcface_torch/train.py
- recognition/arcface_torch/utils/checkpoint.py
- recognition/arcface_torch/utils/utils_callbacks.py
> add resume

- recognition/_datasets_/README.md
Add DigiFace-1M dataset, a newly-released synthetic dataset for face recognition.
Visit https://microsoft.github.io/DigiFace1M/ for more detail.
> Add DigiFace-1M dataset

- recognition/arcface_torch/configs/base.py
- recognition/arcface_torch/train.py
- recognition/arcface_torch/train_v2.py
- recognition/arcface_torch/utils/utils_callbacks.py
WandB for ArcFace. 
WandB will log training and validation results. Default configs are in recognition/arcface_torch/configs/base.py
> Add WandB to arcface_torch.

- recognition/arcface_torch/configs/base.py
- recognition/arcface_torch/docs/install.md
- recognition/arcface_torch/docs/install_dali.md
- recognition/arcface_torch/docs/prepare_webface42m.md
- recognition/arcface_torch/requirement.txt
- recognition/arcface_torch/train.py
- recognition/arcface_torch/train_v2.py
- Dali installation added.
- WebFace Doc updated.
- WandB configs updated.
- Docs Updated.
> Update WebFace, Dali, WandB Configs and Docs.

- python-package/insightface/data/image.py
Fixes https://github.com/deepinsight/insightface/issues/2098
> Make ImageCache optional to prevent memory leak

- python-package/insightface/app/face_analysis.py
> replace np.int with int

- body/human_pose/ambiguity_aware/requirements.txt
There are 1 security vulnerabilities found in torch 1.3.0
- [CVE-2022-45907](https://www.oscs1024.com/hd/CVE-2022-45907)
Upgrade torch from 1.3.0 to 1.13.1 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade torch to 1.13.1

- body/human_pose/ambiguity_aware/scripts/main.py
сhanged concatenation to f-string to improve readability and unify with the rest code
> сhanged concatenation of strings to f-strings to improve readability

- python-package/setup.py
Updated setup.py to make sure there are no build issues when installing insightface.
> Fix macOS installation: Add LLVM check & logging in setup.py
